version: "3.8"

services:
  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: production
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    env_file:
      - .env
    command: ["npx", "pm2-runtime", "server.js"]
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
