services:
  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
      args:
        NODE_ENV: development
    env_file:
      - .env.local
    ports:
      - 3030:3030
      #- "${PORT:-3003}:${PORT:-3003}"
    volumes:
      - .:/home/node/app
      # - /app/node_modules

    command: ["npm", "run", "dev"]
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
