services:
  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: development
    env_file:
      - .env.local
    ports:
      - "${PORT:-3003}:${PORT:-3003}"
    volumes:
      - .:/app
      # - /app/node_modules
    
    command: ["npm", "run", "dev"]
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
