name: Build and Push Docker Image

on:
  push:
    branches:
      - build-image # Workflow ini hanya akan berjalan pada branch 'build-image'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE_TAG: "1.0.0" # Atur tag default, pastikan konsisten dengan docker-compose jika diperlukan
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.CI_REGISTRY }}
          username: ${{ secrets.CI_REGISTRY_USER }}
          password: ${{ secrets.CI_REGISTRY_PASSWORD }}

      - name: Build Docker image (production target)
        run: |
          echo "Disini Build Docker"
          docker build --target production --tag "${{ secrets.CI_REGISTRY_IMAGE }}:${{ env.DOCKER_IMAGE_TAG }}" .

      - name: Push Docker image with tag
        run: |
          docker push "${{ secrets.CI_REGISTRY_IMAGE }}:${{ env.DOCKER_IMAGE_TAG }}"

      - name: Tag image as latest and push
        run: |
          docker image tag "${{ secrets.CI_REGISTRY_IMAGE }}:${{ env.DOCKER_IMAGE_TAG }}" "${{ secrets.CI_REGISTRY_IMAGE }}:latest"
          docker push "${{ secrets.CI_REGISTRY_IMAGE }}:latest"

      - name: Build completed
        run: echo "Build successfully!"
